### ISSUE TITLE
New dataset example

### ISSUE THREAD

**Issue by MarioProjects** [kakaobrain/fast-autoaugment#8]
Could you provide an example of how to use ur technique to find the best policy for another dataset or maybe for CIFAR.

Thanks for your work!

**Comment by ildoonet** [comment]
Hello @MarioProjects, Thanks for your interest.

Currently, we did NOT open 'searching policies' parts although we opened best policies we found on cifar10/100 and imagenet. 

If your new dataset can be considered similar to the one of above datasets, you can 'transfer' the policy to your work. I will revise our code so that you can use our policies with just pip-installed our package. This will require 4-5 weeks, since I will visit US for couple of weeks from the next weekend. But if you want to use the policy and test it ASAP, please follow our codes from here : https://github.com/kakaobrain/fast-autoaugment/blob/master/FastAutoAugment/data.py#L87

If you plan to search policies for your tasks, please wait for our next big release since we are going to open every codes we used for the paper. But for now, we are conducting more experiments on our work and that is why we decided that it would be better to distribute the code in a more complete and clean form even if we released it late.

**Comment by MarioProjects** [comment]
Thanks! I will try to understand the transfer and apply it meanwhile you release the search part.

**Comment by MarioProjects** [comment]
I'm sorry for my lack of understanding. When in the paper you say 'transfer' the augmentations, is this take directly for example those of cifar10 -> your function autoaug_paper_cifar10() and his list of transformations and apply them in a new dataset?

Edit: I should use **fa_reduced_cifar10()** or **autoaug_paper_cifar10()**?

**Comment by ildoonet** [comment]
fa_reduced_cifar10 should be used.

Transfer means searching policies in another dataset(eg. cifar10) with a specific network architecture(eg. wresnet40x2) and transfer the searched policies to the target dataset(eg. cifar100) or to another network(eg. pyramidnet).

**Comment by Manuscrit** [comment]
So to 'transfer' a policy, we only have to apply the chosen policy?

I am looking to train new polices for a domain specific dataset. I believe a simple transfer would not work well.

**Comment by ildoonet** [comment]
@Manuscrit We released the code for search phase. Let me know if you have any problems.

**Comment by Manuscrit** [comment]
Soo cool ! Thanks, I will try it in the next months.
